#!/usr/bin/env bash
#
# Scripts in this directory are run during the build process.
# each script will be uploaded to /tmp on your build droplet,
# given execute permissions and run.  The cleanup process will
# remove the scripts from your build system after they have run
# if you use the build_image task.
#
echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends && \
    echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends && \
    apt-get -q update && \
    apt-get -q install locales && \
    locale-gen en_US.UTF-8 && \
    DEBIAN_FRONTEND=noninteractive apt-get -qy -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" dist-upgrade

wget https://www.zulip.org/dist/releases/zulip-server-latest.tar.gz
tar -xf zulip-server-latest.tar.gz

array=(./zulip-server-*)
"${array[0]}"/scripts/setup/install --email=mail@example.com --hostname "$(hostname -f)" --no-init-db --self-signed-cert

rm -f /etc/zulip/zulip-secrets.conf /etc/zulip/settings.py

# Remove unnessary messages set by Ubuntu that appears during user login.
 rm -f /etc/update-motd.d/00-header
 rm -f /etc/update-motd.d/10-help-text
 rm -f /etc/update-motd.d/51-cloudguest

# The default Ubuntu behavior of the apt-daily.timer systemd job
# results in `apt update` running immediately on boot if it's been
# more than a day since the image was generated.  This can end up
# conflicting with the other `apt` invocations run by the Zulip
# interactive installer.  So we disabled it here and then re-enable it
# once interactive_script.sh completes successfully.
#
# For more details see https://chat.zulip.org/#narrow/stream/3-backend/topic/apt-daily
systemctl disable apt-daily.timer apt-daily-upgrade.timer
