#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

cat <<EOF

Welcome to your Zulip server.

For troubleshooting, maintainance, and support plans, see
* https://zulip.readthedocs.io/en/stable/production/troubleshooting.html
* https://zulip.readthedocs.io/en/stable/production/maintain-secure-upgrade.html
* https://zulipchat.com/plans/

EOF
